#!/bin/sh -x

set -eu

ver="$1"

python --version
pip --version
flit --version

git clean -d -x -f
sed -i "s/^__version__ = .*/__version__ = \"${ver}\"/" src/redis_cache_lock/__init__.py
git commit -am "$ver"
git tag "$ver"
git push
git push --tags
flit upload
